#!/bin/bash
n_nodes=1
max_tokens=15360
# max_tokens=25600
# export WANDB_MODE=offline
export NCCL_P2P_DISABLE=1
export WANDB_API_KEY=
# export HYDRA_FULL_ERROR=1
# export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False
export CUDA_VISIBLE_DEVICES=8,9
n_gpus_per_node=2

export HF_ENDPOINT="https://hf-mirror.com"
export ACCELERATE_LOG_LEVEL=info

export MODEL_PATH=/data1/yxfeng/models/qwen/Qwen2.5-1.5B-Instruct
export DATA_PATH=/data1/yxfeng/data/math
train_path=/data1/yxfeng/data/math/train.parquet
numinaMath_test_path=/data1/yxfeng/data/math/test.parquet
math_test_path=/data1/yxfeng/data/math/test.parquet

train_files="['$train_path']"
test_files="['$numinaMath_test_path','$math_test_path']"

total_epochs=25
total_steps=200
train_batch_size=128
layer=20
loss_weight=0.001
lr=1e-6
run_name=qwen2.5_1.5b_grpo_math_baseline_lora_ep${total_epochs}_lr${lr}

save_root=/data1/yxfeng/grpo/baseline/qwen/Qwen2.5-1.5B-Instruct/math
save_root=${save_root}/${run_name}
mkdir -p $save_root

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$train_files" \
    data.val_files="$test_files" \
    data.train_batch_size=${train_batch_size} \
    data.max_prompt_length=1024 \
    data.max_response_length=1024 \
    data.truncation='right' \
    data.return_full_prompt=True \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.actor.optim.lr=${lr} \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_c=10.0 \
    actor_rollout_ref.actor.optim.warmup_style=cosine \
    actor_rollout_ref.actor.optim.lr_warmup_steps=10 \
    actor_rollout_ref.actor.optim.weight_decay=0.1 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=$max_tokens \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.use_orig_params=False \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.max_model_len=8192 \
    actor_rollout_ref.rollout.max_num_batched_tokens=133120 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.n=7 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.temperature=0.6 \
    actor_rollout_ref.rollout.val_kwargs.top_p=0.7 \
    actor_rollout_ref.rollout.val_kwargs.top_k=-1 \
    actor_rollout_ref.rollout.val_kwargs.do_sample=True \
    actor_rollout_ref.rollout.val_kwargs.n=3 \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.n_gpus_per_node=$n_gpus_per_node \
    trainer.nnodes=${n_nodes} \
    trainer.logger=['console','swanlab'] \
    trainer.project_name=verl_grpo_qwen2.5_1.5b_math \
    trainer.experiment_name=${run_name} \
    trainer.save_freq=50 \
    trainer.test_freq=20 \
    trainer.total_epochs=${total_epochs} \
    trainer.total_training_steps=${total_steps} \
    trainer.default_local_dir=${save_root}/model \
    trainer.rollout_data_dir=${save_root}/rollout \
    trainer.validation_data_dir=${save_root}/val_data \
    trainer.resume_mode=disable